language: go
go:
  - 1.13.x
  - 1.14.x

os:
  - linux
  # - osx

sudo: required

addons:
  apt:
    packages:
      - npm
      - nodejs
      - postgresql

services:
  - postgresql

install:
  - npm install -g create-react-app
  - npm install -g yarn
  - make init-modules

script:
  - # for this project
  - export TEST_PGHOST=localhost TEST_PGPORT=5432 
  - export TEST_DATABASE=task_manager_db TEST_PGUSER=task_manager_user TEST_PGPASSWORD=task_manager_password 
  - make build
  - make test-all
