language: go
go:
  - 1.13.x
  - 1.14.x

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - npm
      - nodejs
      - webpack

install:
  - npm install -g create-react-app
  - npm install -g yarn
  - make init-modules

script:
  - make build
  - make test-all
